packages:
  - apps/*
  - packages/*
  - services/*
allowBuilds:
  '@scarf/scarf': false
  esbuild: true
minimumReleaseAgeExclude:
  - '@nestjs/common@12.1.2'
  - '@nestjs/core@12.1.2'
  - '@nestjs/platform-fastify@12.1.2'
  - '@tanstack/react-router@1.170.41'
  - '@tanstack/router-core@1.171.34'
  - '@tanstack/router-generator@1.167.40'
  - '@tanstack/router-plugin@1.168.42'
  - pg-cloudflare@1.4.1
  - pg-connection-string@2.14.1
  - pg-protocol@1.16.1
  - pg@8.23.1
